### ISSUE TITLE
Importing .less file into bootstrap_and_overrides.css.less

### ISSUE THREAD

**Issue by chrism** [seyhunak/twitter-bootstrap-rails#132]
When I add css directly below the comment it works perfectly - brilliant stuff, love it.

ie

``` css
// Your custom LESS stylesheets goes here

.main-title {
  font-size: 40px;
  color: @grayLight;
}
```

But if I then try to organize that css by moving the styles into separate less files and importing them

ie

``` css
// Your custom LESS stylesheets goes here

@import "controller1styles"
```

controller1styles.css.less

``` css
.main-title {
  font-size: 40px;
  color: @grayLight;
}
```

It blows up with 

``` console
variable @grayLight is undefined
```

Does this mean all css needs to be kept in bootstrap_and_overrides.css.less ?
