### ISSUE TITLE
Mixins generating CSS twice

### ISSUE THREAD

**Issue by simonjefford** [seyhunak/twitter-bootstrap-rails#150]
When I use twitter-bootstrap mixins, the CSS is generated twice. For example:

``` css
#banner {
  #gradient > .vertical(#888, #EEE);
  .box-shadow(0 2px 10px rgba(0, 0, 0, 0.5));
}
```

becomes

``` css
#banner {
  background-color: #b1b1b1;
  background-image: -moz-linear-gradient(top, #888888, #eeeeee);
  background-image: -ms-linear-gradient(top, #888888, #eeeeee);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#888888), to(#eeeeee));
  background-image: -webkit-linear-gradient(top, #888888, #eeeeee);
  background-image: -o-linear-gradient(top, #888888, #eeeeee);
  background-image: linear-gradient(top, #888888, #eeeeee);
  background-repeat: repeat-x;
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#888888', endColorstr='#eeeeee', GradientType=0);
  background-color: #b1b1b1;
  background-image: -moz-linear-gradient(top, #888888, #eeeeee);
  background-image: -ms-linear-gradient(top, #888888, #eeeeee);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#888888), to(#eeeeee));
  background-image: -webkit-linear-gradient(top, #888888, #eeeeee);
  background-image: -o-linear-gradient(top, #888888, #eeeeee);
  background-image: linear-gradient(top, #888888, #eeeeee);
  background-repeat: repeat-x;
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#888888', endColorstr='#eeeeee', GradientType=0);
  -webkit-box-shadow: 0 2px 10px rgba(0, 0, 0, 0.5);
  -moz-box-shadow: 0 2px 10px rgba(0, 0, 0, 0.5);
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.5);
  -webkit-box-shadow: 0 2px 10px rgba(0, 0, 0, 0.5);
  -moz-box-shadow: 0 2px 10px rgba(0, 0, 0, 0.5);
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.5);
}
```

I see this behaviour in both the 2.0.3 gem and from a git checkout of master.

A side question - should I be able to use mixins from any less file included in application.css or do I need to use them from within bootstrap_and_overrides.css?
