### ISSUE TITLE
String interpolation bug in @font-face

### ISSUE THREAD

**Issue by junyat** [seyhunak/twitter-bootstrap-rails#239]
@fontAwesome.+Path variables doesn't expand in @font-face.

results css are

``` css
@font-face {
  font-family: 'FontAwesome';
  src: url("/assets/fontawesome-webfont.eot");
  src: url('@{@fontAwesomeEotPath}?#iefix') format('embedded-opentype'), url("/assets/fontawesome-webfont.woff") format('woff'), url("/assets/fontawesome-webfont.ttf") format('truetype'), url('@{@fontAwesomeSvgzPath}#FontAwesomeRegular') format('svg'), url('@{@fontAwesomeSvgPath}#FontAwesomeRegular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

Here is the diff.

``` diff
index c5d11b9..8df547c 100644
--- a/vendor/toolkit/fontawesome.less
+++ b/vendor/toolkit/fontawesome.less
@@ -28,11 +28,11 @@
 @font-face {
     font-family: 'FontAwesome';
     src: url(@fontAwesomeEotPath);
-    src: url('@{@fontAwesomeEotPath}?#iefix') format('embedded-opentype'),
+    src: url('@{fontAwesomeEotPath}?#iefix') format('embedded-opentype'),
          url(@fontAwesomeWoffPath) format('woff'),
          url(@fontAwesomeTtfPath) format('truetype'),
-         url('@{@fontAwesomeSvgzPath}#FontAwesomeRegular') format('svg'),
-         url('@{@fontAwesomeSvgPath}#FontAwesomeRegular') format('svg');
+         url('@{fontAwesomeSvgzPath}#FontAwesomeRegular') format('svg'),
+         url('@{fontAwesomeSvgPath}#FontAwesomeRegular') format('svg');
     font-weight: normal;
     font-style: normal;
 }
```

I think this is good, but if I set these like this at bootstrap_and_overrides.css.less

``` less
// Set the Font Awesome (Font Awesome is default. You can disable by commenting below lines)
@fontAwesomeEotPath: asset-path('fontawesome-webfont.eot');
@fontAwesomeWoffPath: asset-path('fontawesome-webfont.woff');
@fontAwesomeTtfPath: asset-path('fontawesome-webfont.ttf');
@fontAwesomeSvgzPath: asset-path('fontawesome-webfont.svgz');
@fontAwesomeSvgPath: asset-path('fontawesome-webfont.svg');
```

results are bad.

``` css
@font-face {
  font-family: 'FontAwesome';
  src: url("/assets/fontawesome-webfont.eot");
  src: url('"/assets/fontawesome-webfont.eot"?#iefix') format('embedded-opentype'), url("/assets/fontawesome-webfont.woff") format('woff'), url("/assets/fontawesome-webfont.ttf") format('truetype'), url('"/assets/fontawesome-webfont.svgz"#FontAwesomeRegular') format('svg'), url('"/assets/fontawesome-webfont.svg"#FontAwesomeRegular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

If I set directly string like these

``` less
@fontAwesomeEotPath: '/assets/fontawesome-webfont.eot';
@fontAwesomeWoffPath: '/assets/fontawesome-webfont.woff';
@fontAwesomeTtfPath: '/assets/fontawesome-webfont.ttf';
@fontAwesomeSvgzPath: '/assets/fontawesome-webfont.svgz';
@fontAwesomeSvgPath: '/assets/fontawesome-webfont.svg';
```

results are good and work fine.

``` css
@font-face {
  font-family: 'FontAwesome';
  src: url('/assets/fontawesome-webfont.eot');
  src: url('/assets/fontawesome-webfont.eot?#iefix') format('embedded-opentype'), url('/assets/fontawesome-webfont.woff') format('woff'), url('/assets/fontawesome-webfont.ttf') format('truetype'), url('/assets/fontawesome-webfont.svgz#FontAwesomeRegular') format('svg'), url('/assets/fontawesome-webfont.svg#FontAwesomeRegular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

Do you have any idea to fix this?
