### ISSUE TITLE
CSS styling differences between precompiled assets and dev environment assets in 2.0.7

### ISSUE THREAD

**Issue by tboyko** [seyhunak/twitter-bootstrap-rails#245]
I am finding that bootstrap elements are rendering with different CSS depending upon if I'm running a site in the development environment versus production with precompiled assets. I've seen this issue come up in two of my projects, and it started after upgrading to 2.0.7, so I'm tempted to think that there's a bug or interop issue present.

The most simple example I have of this issue is in the .brand tag. In dev, I see this:

``` css
.navbar .brand {
float: left;
display: block;
padding: 8px 20px 12px;
margin-left: -20px;
font-size: 20px;
font-weight: 200;
line-height: 1;
color: #ffffff;
}
```

In production:

``` css
.navbar .brand {
float: left;
display: block;
padding: 8px 20px 12px;
margin-left: -20px;
font-size: 20px;
font-weight: 200;
line-height: 1;
color: #999999;
}
```

Notice the change in the color tag. I saw a similar issue that had to do with margins around a link and an image, but it was less concrete and more likely to be an issue of my own.
