### ISSUE TITLE
2.1.0 - fontawesome.less sprite reset causes ie7 not to display sprites

### ISSUE THREAD

**Issue by sr75** [seyhunak/twitter-bootstrap-rails#273]
2.1.0 - fontawesome.less sprite reset causes ie7 not to display sprites

When commenting out the following snippet in fontawesome.less _sprites will show up_ in ie7:

``` css
/* sprites.less reset */
[class^="icon-"],
[class*=" icon-"] {
    display: inline;
    width: auto;
    height: auto;
    line-height: inherit;
    vertical-align: baseline;
    background-image: none;
    background-position: 0% 0%;
    background-repeat: repeat;
}
```

Here's the source twitter-bootstrap sprite.less part being reset is:

``` css
[class^="icon-"],
[class*=" icon-"] {
  display: inline-block;
  width: 14px;
  height: 14px;
  .ie7-restore-right-whitespace();
  line-height: 14px;
  vertical-align: text-top;
  background-image: url(@iconSpritePath);
  background-position: 14px 14px;
  background-repeat: no-repeat;
}
```

There's an ie7 specific fix from twitter-bootstrap in this less being reset.  So the fontawesome reset looks to be causing a conflicting override for the ie7 fix twitter put in.  All other > ie7 and other major browsers don't seem to be affected by the reset so we couldn't find any drawbacks for undoing the reset to make sprites show up in ie7.

Just a thought, I really like the fontawesome stuff, but it would probably better to have it split out as an extension to this gem.   Keeping this gem to just core twitter-bootstrap style/functionality would make it much easier to test and track down/isolate core style issues going forward.
