### ISSUE TITLE
Missing Bootstrap JS Files In Production

### ISSUE THREAD

**Issue by cogmation** [seyhunak/twitter-bootstrap-rails#335]
I was having a problem in production mode, all my css files are included but I'm missing all the js files that should be included using the `//= require twitter/bootstrap` directive in my `application.js` file.

This is the contents of my application.js file:

``` javascript
//= require jquery
//= require jquery_ujs
//= require twitter/bootstrap

```

In my layout I load the file as so:

``` Rails
<%= javascript_include_tag "application", "tabs", "jquery.colorbox", "jquery.easing.1.3" %>
```

I include the twitter-bootstrap-rails gem in my assets group within my GemFile, from the looks of the JavaScript load issues on my production website (http://lists.cogmation.com) in firebug console it's looking for pre-compiled assets and not finding them. 

I should again note that I have no problem loading the css files and the js files are loaded perfectly fine in development mode. 

I think the problem is that I'm unable to pre-compile my assets. After attempting `rake assets:precompile` I receive this output:

``` Rails
Invalid CSS after "...f.eot);src:url(": expected expression (e.g. fr, 2n+1), was "/assets/"/asset..."
```

This could have something to do with the fonts being loaded apparently so here's the relevant code from my bootstrap.less file and font-awesome.less file:

Font-awesome.less:

``` less
@font-face {
  font-family: 'FontAwesome';
  src: url('/assets/fontawesome-webfont.eot');
  src: url('/assets/fontawesome-webfont.eot?#iefix') format('embedded-opentype'),
    url('/assets/fontawesome-webfont.woff') format('woff'),
    url('/assets/fontawesome-webfont.ttf') format('truetype'),
    url('/assets/fontawesome-webfont.svg#FontAwesome') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

bootstrap_and_override.css.less:

``` less
@fontAwesomeEotPath: asset-path('fontawesome-webfont.eot');
@fontAwesomeWoffPath: asset-path('fontawesome-webfont.woff');
@fontAwesomeTtfPath: asset-path('fontawesome-webfont.ttf');
@fontAwesomeSvgzPath: asset-path('fontawesome-webfont.svgz');
@fontAwesomeSvgPath: asset-path('fontawesome-webfont.svg');
```
