### ISSUE TITLE
glyphicons-halflings.png not loaded in production if the rails app is deployed in a subdirectory 

### ISSUE THREAD

**Issue by hrigu** [seyhunak/twitter-bootstrap-rails#346]
My rails app _my_app_ is deployed with Passenger and apache under the subdirectory _rails/_. So the link to my_apps home is _<host>/rails/_

But the browser can't load bootstrap's _glyphicons-hlflings.png_ file because the url doesn't reflect the _rails_ part.

Here the snipped out of the compiled css file:

``` css
icon-white {
background-image: url("/assets/twitter/bootstrap/glyphicons-halflings-white-13553a5bf21ae3cc374006592488ec64.png");
}
```

when I change the following line in _bootstrap-and-overrides.css.less_

``` less
@iconSpritePath: asset-path('twitter/bootstrap/glyphicons-halflings.png');
```

to

``` less
@iconSpritePath: asset-url('twitter/bootstrap/glyphicons-halflings.png');
```

Then the image can be loaded. The URL is now relative to the css file, which is ok:

``` css
icon-white {
background-image: url("twitter/bootstrap/glyphicons-halflings-white-13553a5bf21ae3cc374006592488ec64.png");
}
```

But unfortunately this change breaks the developer mode: Less compiles the url to  the strange string, _url(url(/assets/tw..._ 

``` css
.icon-white {
  background-image: url(url(/assets/twitter/bootstrap/glyphicons-halflings-white.png));
}
```

So the file can't be loaded in development mode

Any hints?

Christian
