### ISSUE TITLE
Firefox: invalid version tag (fontawesome-webfont.eot?#iefix)

### ISSUE THREAD

**Issue by manu3569** [seyhunak/twitter-bootstrap-rails#370]
The two errors below are logged by Firefox upon page loads. Any ideas as to what's causing it.
### Related:

https://github.com/seyhunak/twitter-bootstrap-rails/issues/292
### Firefox Errors:

```
Timestamp: 9/15/12 12:44:12 PM
Error: downloadable font: invalid version tag (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:0)
source: http://0.0.0.0:3000/assets/fontawesome-webfont.eot?#iefix
Source File: http://0.0.0.0:3000/assets/application.css
Line: 0
Source Code:
@font-face {   font-family: "FontAwesome";   font-style: normal;   font-weight: normal;   src: url("/assets/fontawesome-webfont.eot?#iefix"), url("/assets/fontawesome-webfont.woff"), url("/assets/fontawesome-webfont.ttf"), url("/assets/fontawesome-webfont.svg#FontAwesome"); }


Timestamp: 9/15/12 12:44:12 PM
Error: downloadable font: rejected by sanitizer (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:0)
source: http://0.0.0.0:3000/assets/fontawesome-webfont.eot?#iefix
Source File: http://0.0.0.0:3000/assets/application.css
Line: 0
Source Code:
@font-face {   font-family: "FontAwesome";   font-style: normal;   font-weight: normal;   src: url("/assets/fontawesome-webfont.eot?#iefix"), url("/assets/fontawesome-webfont.woff"), url("/assets/fontawesome-webfont.ttf"), url("/assets/fontawesome-webfont.svg#FontAwesome"); }
```
### application.css - excerpt

``` css
@font-face{font-family:'FontAwesome';src:url("/assets/fontawesome-webfont.eot");src:url("/assets/fontawesome-webfont.eot?#iefix"),url("/assets/fontawesome-webfont.woff"),url("/assets/fontawesome-webfont.ttf"),url("/assets/fontawesome-webfont.svg#FontAwesome");font-weight:normal;font-style:normal}
```
### boostrap_and_overrides.css.less

``` css
@fontAwesomeEotPath: "/assets/fontawesome-webfont.eot";
@fontAwesomeWoffPath: '/assets/fontawesome-webfont.woff';
@fontAwesomeTtfPath: '/assets/fontawesome-webfont.ttf';
@fontAwesomeSvgPath: '/assets/fontawesome-webfont.svg';

// Font Awesome
@import "fontawesome";
```
### Environment:

Firefox: 15.0.1
Using less-rails (2.2.3) 
Using rails (3.2.8) 
Using twitter-bootstrap-rails (2.1.3) from git://github.com/seyhunak/twitter-bootstrap-rails.git (at master)
