### ISSUE TITLE
Use count instead of pluralize

### ISSUE THREAD

**Issue by dsimard** [seyhunak/twitter-bootstrap-rails#508]
In the views generated by scaffold, it would be better to use `count` instead of `pluralize` (see this line : https://github.com/seyhunak/twitter-bootstrap-rails/blob/v2.1.0/lib/generators/bootstrap/themed/templates/index.html.erb#L3).

`pluralize` doesn't care about the locales. Example, I have this `fr.yml` file :

```
activerecord:
  models:
    broomstick:
      one: Manche à balai
      other: Manches à balai
```

`pluralize` will display 'manche à balais' instead of 'manches à balai' as specified in the locale file.

The line should be something like :

```
model_class.model_name.human(count:@broomsticks.size)
```
