### ISSUE TITLE
Don't have style for .carousel-indicators

### ISSUE THREAD

**Issue by unrealhoang** [seyhunak/twitter-bootstrap-rails#542]
I'm currently using twitter-bootstrap-rails version 2.1.4
My current bootstrap_and_override.less:

``` css
@import "twitter/bootstrap/bootstrap";
body { padding-top: 60px; }
@import "twitter/bootstrap/responsive-utilities";
@import "twitter/bootstrap/responsive-768px-979px";
@import "twitter/bootstrap/responsive-767px-max";
@import "twitter/bootstrap/responsive-navbar";

// Set the correct sprite paths
@iconSpritePath: asset-path("twitter/bootstrap/glyphicons-halflings");
@iconWhiteSpritePath: asset-path("twitter/bootstrap/glyphicons-halflings-white");

// Set the Font Awesome (Font Awesome is default. You can disable by commenting below lines)
// Note: If you use asset_path() here, your compiled bootstrap_and_overrides.css will not
//       have the proper paths. So for now we use the absolute path.
@fontAwesomeEotPath: asset-path("fontawesome-webfont.eot");
@fontAwesomeEotPath_iefix: asset-path("fontawesome-webfont.eot#iefix");
@fontAwesomeWoffPath: asset-path("fontawesome-webfont.woff");
@fontAwesomeTtfPath: asset-path("fontawesome-webfont.ttf");
@fontAwesomeSvgPath: asset-path("fontawesome-webfont.svg");

// Font Awesome
@import "fontawesome";

// Glyphicons
//@import "twitter/bootstrap/sprites.less";

// Your custom LESS stylesheets goes here
//
// Since bootstrap was imported above you have access to its mixins which
// you may use and inherit here
//
// If you'd like to override bootstrap's own variables, you can do so here as well
// See http://twitter.github.com/bootstrap/customize.html#variables for their names and documentation
//
// Example:
// @linkColor: #ff0000;
```

But there was no style definition for .carousel-indicators, and, as a result, I have to put it in manually.
![Screen Shot 2013-03-10 at 11 26 03 PM](https://f.cloud.github.com/assets/1218094/241266/4b8ea500-899f-11e2-9793-b17fa7f86fb7.png)
