### ISSUE TITLE
Mixins like makeColumn aren't working

### ISSUE THREAD

**Issue by eligundry** [seyhunak/twitter-bootstrap-rails#547]
I'm trying to use mixins in files that are in Rails asset pipeline and am getting `Less::ParseError`s. Here's some of my code:
### application.css

``` css
/*                                                                                                               
 *= require_self                                                                                                 
 *= require_tree .                                                                                               
 *= require bootstrap_and_overrides                                                                                                                                                                                                
 *= require bootstrap-datepicker                                                                                 
 */   
```
### bottom of my bootstrap_and_overrides.css.less

``` less
.bottom-footer {                                                                                       
    .makeRow();                                                                                        

    ul {                                                                                               
        .makeColumn(2);                                                                                
        list-style: none;                                                                              
    }                                                                                                  
}  
```
### home.css.less

``` less
.cert-process {
       .makeRow();
    .process-signup {
        .makeColumn(4);
    }

    .process-list {
        .makeColumn(8);
    }
}
```

It's worth noting that the mixin in the `bootstrap_and_overrides.css.less` are working without a problem, but the ones in other files fail and throw errors.
