### ISSUE TITLE
Breadcrumb without dividers

### ISSUE THREAD

**Issue by anatoly-cmdx** [seyhunak/twitter-bootstrap-rails#882]
When using this gem you'll actually get **two** dividers:

One is inserted by this gem as `<span class="divider ">/</span>`
And another one is defined by bootstrap for `breadcrumb` class:
```css
.breadcrumb > li + li::before {
    ...
    content: "/ ";
    ...
}
```

A simple workaround is:
```erb
    <%= render_breadcrumbs('') %>
```
which just generates empty dividers `<span class="divider "></span>`

But I think there should be a way render breadcrumbs without dividers at all.
